### ISSUE TITLE
wss

### ISSUE THREAD

**Issue by mre30** [sclausen/ngx-mqtt#39] opened 2017-08-08 07:59 UTC
Hi,
There is issue in case of wss:
_failed: Error during WebSocket handshake: Unexpected response code: 301_

```
export const MQTT_SERVICE_OPTIONS = {
  hostname: 'test.com/mqtt/'
};
```
If i try this:

```
export const MQTT_SERVICE_OPTIONS = {
  connectOnCreate: false,
  hostname: 'test.com/mqtt/',
  port: 80,
  protocol: 'wss',
  path: '/mqtt'
};
```
Getting error inside editor: 
_Argument of type '{ connectOnCreate: boolean; hostname: string; port: number; protocol: string; path: string; }' is not assignable to parameter of type 'MqttServiceOptions'.
  Types of property 'protocol' are incompatible.
    Type 'string' is not assignable to type '"wss" | "ws"'._

Thanks

**Comment by sclausen** [comment] 2017-08-08 08:22
I see two different problems here. On the first hand, you've got a 301, which indicates, that this host has moved. You've set the port to 80. Does a broker really listens to that port? using the standard http port for an mqtt endpoint seems unfamiliar to me.

The typing problem in your editor though is pretty mysterious, since the type 'wss' | 'ws' totally fits for your options… Which typescript version do you use?

**Comment by mre30** [comment] 2017-08-08 08:32
Yeap, i is quite strange. The version is : Version 2.2.3

Error in console log is the same as in editor of course.

Thank you

**Comment by sclausen** [comment] 2017-08-08 08:33
Would you be so kind and post the complete error and maybe a screenshot or something?

**Comment by mre30** [comment] 2017-08-08 08:42
Yes sure:
https://ibb.co/jBHvga
https://ibb.co/bZUVEv

```
Argument of type '{ connectOnCreate: boolean; hostname: string; port: number; protocol: string; path: string; }' is not assignable to parameter of type 'MqttServiceOptions'.
  Types of property 'protocol' are incompatible.
    Type 'string' is not assignable to type '"wss" | "ws"'.
```

**Comment by sclausen** [comment] 2017-08-08 08:51
Thanks for the screenshots, but I really need more information. A complete repository with the stripped down problem would be great.
The code works for me, so without any further configuration of your setup, I really can't dig more into this issue.

Besides all of that. This type error is not the cause of your *Unexpected response code: 301* Did you fixed that part? Did you ensure the port is correct for a websocket endpoint of a mqtt broker?

**Comment by mre30** [comment] 2017-08-08 09:00
mm, the point is that in this case it does not matter 301 redirect is fixed or not, because this type of error is inside the code.. 

About connection - when i am connecting to it with normal Paho javascript library with wss it works normally without any troubles, so it means if from ngx will connect to wss - it will work.

But again, this error i am getting is inside library.

Regarding the repository, i will try to give you everything i can  get:


```
errors | @ | client?ffdb:119
-- | -- | --
  | sock.onmessage | @ | socket.js:37
  | webpackJsonp.../../../../sockjs-client/lib/event/eventtarget.js.EventTarget.dispatchEvent | @ | eventtarget.js:51
  | (anonymous) | @ | main.js:274
  | webpackJsonp.../../../../sockjs-client/lib/main.js.SockJS._transportMessage | @ | main.js:272
  | webpackJsonp.../../../../sockjs-client/lib/event/emitter.js.EventEmitter.emit | @ | emitter.js:50
  | WebSocketTransport.ws.onmessage | @ | websocket.js:35
  | wrapFn | @ | zone.js:1069
  | webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask | @ | zone.js:424
  | webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask | @ | zone.js:191
  | webpackJsonp.../../../../zone.js/dist/zone.js.ZoneTask.invokeTask | @ | zone.js:498
  | invokeTask | @ | zone.js:1364
  | globalZoneAwareCallback
```


```
WebSocketStream | @ | stream.js:77
-- | -- | --
  | createWebSocket | @ | ws.js:59
  | buildBuilderBrowser | @ | ws.js:85
  | wrapper | @ | index.js:138
  | webpackJsonp.../../../../ngx-mqtt/node_modules/mqtt/lib/client.js.MqttClient._setupStream | @ | client.js:237
  | webpackJsonp.../../../../ngx-mqtt/node_modules/mqtt/lib/client.js.MqttClient._reconnect | @ | client.js:606
  | (anonymous) | @ | client.js:621
  | webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask | @ | zone.js:424
  | onInvokeTask | @ | core.es5.js:4151
  | webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask | @ | zone.js:423
  | webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask | @ | zone.js:191
  | webpackJsonp.../../../../zone.js/dist/zone.js.ZoneTask.invokeTask | @ | zone.js:498
  | ZoneTask.invoke | @ | zone.js:487
  | timer
```
Maybe i should try to update typescript again?
Thanks.

**Comment by sclausen** [comment] 2017-08-08 09:20
Maybe a new typescript version will work. Maybe…
Can you post me your tsconfig and the package.json? 
Did you tried to type the MQTT_SERVICE_OPTIONS with MqttServiceOptions like the following?

``` typescript
export const MQTT_SERVICE_OPTIONS: MqttServiceOptions = {
  connectOnCreate: false,
  hostname: 'test.com/mqtt/',
  port: 80,
  protocol: 'wss',
  path: '/mqtt'
};
```
Regarding your 301 problem: I also get the error using the hivemq websocket client demo
![301](https://user-images.githubusercontent.com/916076/29065108-5817ce2c-7c2b-11e7-9c77-3a2a1884eaa3.png)

**Comment by mre30** [comment] 2017-08-08 09:39
Now i tried to include MqttServiceOptions from 'ngx-mqtt' and put it like your example and error disappeared :)

But now i have another problem that is 

```
ERROR Error: mqtt client not connected
    at MqttService.webpackJsonp.../../../../ngx-mqtt/src/mqtt.service.js.MqttService.observe (mqtt.service.js:148)
    at new SmartmeterInfoDefaultComponent (smartmeter-info-default.component.ts:57)
    at createClass (core.es5.js:10597)
    at createDirectiveInstance (core.es5.js:10436)
    at createViewNodes (core.es5.js:11870)
    at createRootView (core.es5.js:11765)
    at callWithDebugContext (core.es5.js:13152)
    at Object.debugCreateRootView [as createRootView] (core.es5.js:12469)
    at ComponentFactory_.webpackJsonp.../../../core/@angular/core.es5.js.ComponentFactory_.create (core.es5.js:9546)
    at ComponentFactoryBoundToModule.webpackJsonp.../../../core/@angular/core.es5.js.ComponentFactoryBoundToModule.create (core.es5.js:3578)
```

Trying to fix it.

P.s test.com/mqtt is just test string, not actually Mqtt service, for some reasons i can not post it here, but if it is possible i will send you it in private message.

May i ask you?
In app module.ts i put this configuration:
```
/* MQTT */
import { MqttMessage, MqttModule,MqttService, MqttServiceOptions } from 'ngx-mqtt';

export const MQTT_SERVICE_OPTIONS: MqttServiceOptions = {
  connectOnCreate: false,
  hostname: 'test.com/mqtt',
  port: 80,
  protocol: 'wss',
  path: '/'
};

export function mqttServiceFactory() {
  return new MqttService(MQTT_SERVICE_OPTIONS);
}
/* /MQTT */
```

And from some component i am trying this:
```
import { Observable } from 'rxjs/Observable';
import { MqttMessage, MqttModule, MqttService } from 'ngx-mqtt';

export class SomeComponent implements OnInit{

  constructor(private _mqttService: MqttService) {
    this._mqttService.observe('some/test/value/#').subscribe((message: MqttMessage) => {
      this.myMessage = message.payload.toString();
      console.log(message.payload.toString());
    });
    this.myOtherMessage$ = this._mqttService.observe('some/test/value/#');
   }

  public unsafePublish(topic: string, message: string): void {
    this._mqttService.unsafePublish(topic, message, {qos: 1, retain: true});
  }
  

}
```

Is this structure properly?

Thanks.

**Comment by mre30** [comment] 2017-08-08 11:28
Any advice?

**Comment by sclausen** [comment] 2017-08-11 11:29
Basically this is right, but keep in mind you have to connect manually, if you use `connectOnCreate: false`.

You still didn't gave me your package.json I really don't want to be rude, but you know, I'm not a wizard and throwing small pieces of information at me from time to time isn't really helping. Since this isn't a bug, but a misconfiguration on your side, I'm really sad I have to close this issue for now.

**Closed by sclausen** 2017-08-11 11:29 UTC

**Comment by mre30** [comment] 2017-08-11 11:35
Hi Sclausen,
Here is package.json
```
{
    "name": "app",
    "version": "0.0.0",
    "license": "MIT",
    "scripts": {
        "ng": "ng",
        "start": "ng serve",
        "build": "ng build",
        "test": "ng test",
        "lint": "ng lint",
        "e2e": "ng e2e"
    },
    "private": true,
    "dependencies": {
        "@angular/animations": "^4.0.0",
        "@angular/common": "^4.0.0",
        "@angular/compiler": "^4.0.0",
        "@angular/core": "^4.0.0",
        "@angular/forms": "^4.0.0",
        "@angular/http": "^4.0.0",
        "@angular/platform-browser": "^4.0.0",
        "@angular/platform-browser-dynamic": "^4.0.0",
        "@angular/router": "^4.0.0",
        "angular2-mqtt": "^1.7.1",
        "core-js": "^2.4.1",
        "ngx-mqtt": "^1.13.0",
        "rxjs": "^5.4.1",
        "zone.js": "^0.8.14"
    },
    "devDependencies": {
        "@angular/cli": "^1.2.7",
        "@angular/compiler-cli": "^4.0.0",
        "@angular/language-service": "^4.0.0",
        "@types/jasmine": "~2.5.53",
        "@types/jasminewd2": "~2.0.2",
        "@types/node": "~6.0.60",
        "codelyzer": "~3.0.1",
        "jasmine-core": "~2.6.2",
        "jasmine-spec-reporter": "~4.1.0",
        "karma": "~1.7.0",
        "karma-chrome-launcher": "~2.1.1",
        "karma-cli": "~1.0.1",
        "karma-coverage-istanbul-reporter": "^1.2.1",
        "karma-jasmine": "~1.1.0",
        "karma-jasmine-html-reporter": "^0.2.2",
        "protractor": "~5.1.2",
        "ts-node": "~3.0.4",
        "tslint": "~5.3.2",
        "typescript": "~2.3.3"
    }
}
```
