### ISSUE TITLE
upgrade to 6.11.0 breaks existing functionality

### ISSUE THREAD

**Issue by argupta23** [sclausen/ngx-mqtt#139] opened 2019-07-14 00:53 UTC
- [x ] **I have searched for similar issues in this repository, but couldn't find one.**
- [x] **I have read the README and have a basic understanding how angular works.**
## I'm submitting a...

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x ] Bug report  
- [ ] Feature request

## Current behavior
Upgrading from ver 6.10.0 to 6.11.0 results in the below error message being reported in the console.

TypeError: _angular_core__WEBPACK_IMPORTED_MODULE_0__.\u0275\u0275defineInjectable is not a function
mqtt.service.js:390:34
    MqttService mqtt.service.js:390
    js mqtt.service.js:400
    Webpack 14
        __webpack_require__
        js
        __webpack_require__
        js
        __webpack_require__
        ts
        __webpack_require__
        ts
        __webpack_require__
        0
        __webpack_require__
        checkDeferredModules
        webpackJsonpCallback
        <anonymous>
[WDS] Warnings while compiling. client:148
./node_modules/ngx-mqtt/src/mqtt.service.js 390:34-55
"export 'ɵɵdefineInjectable' (imported as 'i0') was not found in '@angular/core' client:154
./node_modules/ngx-mqtt/src/mqtt.service.js 390:126-137
"export 'ɵɵinject' (imported as 'i0') was not found in '@angular/core' client:154
./node_modules/ngx-mqtt/src/mqtt.service.js 390:161-172
"export 'ɵɵinject' (imported as 'i0') was not found in '@angular/core' client:154
./node_modules/@angular/compiler/src/util.js 10:24-31
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

## Expected behavior
upgrade should not break existing functionality

## What is the motivation / use case for changing the behavior?
Bug

## Environment

"@angular/animations": "^7.2.15",
    "@angular/cdk": "^7.3.7",
    "@angular/common": "^7.2.15",
    "@angular/compiler": "^7.2.15",
    "@angular/core": "^7.2.15",
    "mqtt": "^2.18.8",
<pre><code>
ngx-mqtt version: 6.11.0

- Broker Mosquitto

Others:

Happy to share any more information if needed.

**Comment by sclausen** [comment] 2019-07-14 10:07
Duplicate of #138

**Closed by sclausen** 2019-07-14 10:07 UTC
