### ISSUE TITLE
double messages while using mosquitto + websocket

### ISSUE THREAD

**Issue by ramarro123** [sclausen/ngx-mqtt#26] opened 2017-06-15 13:04 UTC
hello,

i try to connect to my local mosquitto server with

>  this.mqtt = new MqttService({
>       hostname: localhost,
>       port: 9001,
>       path: '/',
>       protocol: 'ws',
>       username: user,
>       password: pwd,
>       connectOnCreate:true
>     });

and then observer for meteo topic with

>   this.mqtt.observe('meteo').subscribe((message:MqttMessage) => {
>         let meteo:METEO = JSON.parse(message.payload.toString());
>         console.log("meteo", meteo);
>       },
>       (err) => {
>         console.log("error?");
>       });
> 

i got the "meteo" log twice, even if the publisher publish only 1 message with 
2, true as flags (publisher it's an esp board)

using MQTT lens on chrome, give correct results (when i start observing meteo, i got 1 message, cos the message it's 2 (exact flag) and retain = true (so there is always one msg on the mqtt broker with meteo information)

i am pretty sure that this things comes out after an npm update, but i can't really confirm mych more :(

**Comment by sclausen** [comment] 2017-06-17 07:29
That sounds bad. I'll have a look at this issue this weekend.

**Comment by sclausen** [comment] 2017-06-19 06:49
I can't reproduce your problem. Do you really only subscribe once to meteo? do you have a # wildcard subscription too? Or maybe a general on message handler?

**Comment by ramarro123** [comment] 2017-06-19 07:34
no, i subscribe to meteo only once, nor to other sub/meteo/# things.
mqttlens give me correct results on msg on the "stack" (meteo it's a retain message)


i am quite puzzled too

with
/usr/local/mosquitto/bin/mosquitto_sub -P user -u pwd -h localhost -t "#" -v

i see the correct stack of expected retain message (1 meteo, 1 settings and some other retain message)

for some reason when i connect with angular i got twice.


it may be worth to mention that i get TWICE messages retained on connect.
single topic, send with mosquitto_pub or with arduino, are delivered once, so seems that the problem it's only on connect phase with retain messages.

**Comment by sclausen** [comment] 2017-06-19 09:27
Ah, yes, now I can reproduce!

**Comment by ramarro123** [comment] 2017-06-19 09:33
sorry :( 

next time i'll try to give you more infos from the very begin :)

**Comment by sclausen** [comment] 2017-06-19 09:33
The issue originated from a now fixed bug in MQTT.js. I just upgraded the dependency and now it seems to work. Could you try `ngx-mqtt@1.11.0` and confirm?

**Comment by ramarro123** [comment] 2017-06-19 09:41
work for me, tnx

**Closed** 2017-06-19 10:37 UTC
